#ifndef __IntConnectorSourceDlg__
#define __IntConnectorSourceDlg__

/**
@file
Subclass of ConnectorSourceDlg, which is generated by wxFormBuilder.
*/

#include "connectorgui.h"
#include "data_source.h"
//// end generated include

/** Implementing ConnectorSourceDlg */
class IntConnectorSourceDlg : public ConnectorSourceDlg
{
	protected:
		// Handlers for ConnectorSourceDlg events.
		void OnComSelected( wxCommandEvent& event );
		void OnNetSelected( wxCommandEvent& event );
		void OnCancelClick( wxCommandEvent& event );
		void OnOkClick( wxCommandEvent& event );
	public:
		/** Constructor */
		IntConnectorSourceDlg( wxWindow* parent );
		
	//// end generated class members
	DataSource mDataSource;
};

#endif // __IntConnectorSourceDlg__
