#ifndef __IntStatusDlg__
#define __IntStatusDlg__

/**
@file
Subclass of StatusDlg, which is generated by wxFormBuilder.
*/

#include "connectorgui.h"

//// end generated include

/** Implementing StatusDlg */
class IntStatusDlg : public StatusDlg
{
	protected:
		// Handlers for StatusDlg events.
		void OnCheckListBox( wxCommandEvent& event );
		void OnCheckListBoxToggled( wxCommandEvent& event );
	public:
		/** Constructor */
		IntStatusDlg( wxWindow* parent );
	//// end generated class members
	
};

#endif // __IntStatusDlg__
